spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${HOST:localhost}:${PORT:5432}/${DBName:postgres}?currentSchema=${SCHEMA:car-service}
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME:postgres}
    password: ${PASSWORD:Nurlan2006,}
    hikari:
      minimum-idle: 2
      idle-timeout: 40000
      maximum-pool-size: 10
      connection-timeout: 10000
      keepalive-time: 30000
      schema: public
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true

  sql:
    init:
      schema-locations: ${SCHEMA}
  threads:
    virtual:
      enabled: true