server:
  servlet:
    context-path: /cars-app
spring:
  liquibase:
    enabled: false
    change-log: src/main/resources/db.changelog/tbl-brand/20260126-create-tbl-brand.yaml
  jpa:
    hibernate:
      ddl-auto:
        update
    show-sql: true
  profiles:
    active:
      local
  application:
    name: local
  datasource:

    url: jdbc:postgresql://localhost:5432/car-service
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver


    hikari:
      schema: ${SCHEMA}
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 40000
      maximum-pool-size: 10
      connection-timeout: 10000
      keepalive-time: 30000

jwt:
  secret: "CHANGE_TO_32+_CHAR_RANDOM_SECRET"
  access-exp: 360_000      # 5 min
  refresh-exp: 420_000     # 7 min

